# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "The Coop Blog"
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  This blog is the informal and conversational outlet for the Bioinformatics & Data Science Cooperative at Fred Hutch.
# twitter_username: username
# github_username: username
minimal_mistakes_skin: contrast
search: true
  
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.17.2

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
encoding: UTF-8

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FredHutch/coop"
    - label: "Coop Slack"
      icon: "fab fa-fw fa-slack"
      url: "https://fhbig.slack.com/"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true # this is if you want to allow people to share the post on their own social media
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
  # _contributors
  - scope:
      path: "_contributors"
      type: contributors
    values:
      layout: single
      share: false
      
category_archive:
  type: liquid
  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/

collections:
  contributors:
    output: true
    permalink: /:collection/:path/

# Analytics
analytics:
  provider: "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-153287171-1
